# Basic
title: 云见数据分析
subtitle: 你好，我是齐云涧
welcome_message: #<a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 学院派广告优化师，广告数据定量分析布道者
creator: <a href="http://onev.cat">@云见数据分析</a>

url: "zhuanlan.zhihu.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 干货分享
    description: 互联网数据分析的道与术

# Navigation buttons in the front page.
nav:
    - {title: 我的知乎, description: , url: 'https://zhuanlan.zhihu.com/yunjiandataanalysis'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    #github: onevcat
    #twitter: onevcat
    #gplus: 
    mail: qyunjian@foxmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
